<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-MVN1TR0E" failures="0" tests="7" name="Demo.AppiumFramework.HybridTestCases" time="0.012" errors="1" timestamp="2023-05-17T15:13:39 IST" skipped="6">
  <testcase classname="Demo.AppiumFramework.HybridTestCases" name="login" time="0.001">
    <skipped/>
  </testcase> <!-- login -->
  <system-out/>
  <testcase classname="Demo.AppiumFramework.HybridTestCases" name="Hsetup" time="0.011">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:149)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
at java.base/java.io.FileReader.<init>(FileReader.java:60)
at Demo.AppiumFramework.HybridCapabilities.hybridCapability(HybridCapabilities.java:26)
at Demo.AppiumFramework.HybridTestCases.Hsetup(HybridTestCases.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:644)
at org.testng.TestRunner.beforeRun(TestRunner.java:633)
at org.testng.TestRunner.run(TestRunner.java:595)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Hsetup -->
  <system-out/>
  <testcase classname="Demo.AppiumFramework.HybridTestCases" name="checkPrice" time="0.000">
    <skipped/>
  </testcase> <!-- checkPrice -->
  <system-out/>
  <testcase classname="Demo.AppiumFramework.HybridTestCases" name="visitWeb" time="0.000">
    <skipped/>
  </testcase> <!-- visitWeb -->
  <system-out/>
  <testcase classname="Demo.AppiumFramework.HybridTestCases" name="AddToCart">
    <skipped/>
  </testcase> <!-- AddToCart -->
  <system-out/>
  <testcase classname="Demo.AppiumFramework.HybridTestCases" name="AddToCartSinglepro">
    <skipped/>
  </testcase> <!-- AddToCartSinglepro -->
  <system-out/>
  <testcase classname="Demo.AppiumFramework.HybridTestCases" name="InvalidLogin">
    <skipped/>
  </testcase> <!-- InvalidLogin -->
  <system-out/>
</testsuite> <!-- Demo.AppiumFramework.HybridTestCases -->
